### PR TITLE
initial ruby on rails best practices

### LINKED ISSUE #2: Document Ruby / Rails

### PR DESCRIPTION
**Pull request by JPrevost**
closes #2

### CODE REVIEW

**Comment by gravesm** [comment]
Make sure you add a link to this from the front page.

**Comment by JPrevost** [comment]
Good catch. Just pushed up the file I forgot to include @gravesm

**Comment by gravesm** [comment]
:+1:

**Comment by JPrevost** [comment]
I'm going to move the subsections out of the README and squash this up before merging.

**Pull request merged**
